### PR TITLE
fix build on Windows

### PR DESCRIPTION
**Pull request by dev-zzo**
This makes sure that at least `date` output gets properly integrated and does not break the build completely. The format is different from -nix though, but seems to work fine.

### CODE REVIEW

**Comment by geo-rg** [comment]
On Linux, this breaks the building process for me. I suppose you changed something on the build date for Linux? Maybe you can fix this and contribute the solution?

Thank you very much for your effort!

**Comment by dev-zzo** [comment]
I see how this breaks things. Will push another commit to bring things in order.

**Comment by dev-zzo** [comment]
This should do it.

**Comment by geo-rg** [comment]
Works well for me using linux. Thanks for your quick response and thanks for your contribution!

**Pull request merged**
