### PR TITLE
Faster ISR sharing in ASM

### PR DESCRIPTION
**Pull request by ceres-c**
While in the process of writing a new codec I stumbled upon the long
standing issue of ISR sharing in AVR MCUs.
Actually this is accomplished with an ISR written in C, which simply
calls another plain C function referenced via a function pointer
updated at runtime.
This approach is slow because GCC can't optimize the ISR, since it
does not know which registers will be used, so it defaults to push/pop
all of them.

My solution keeps the concept of pointers to functions, but greatly
improves speed by reducing the ISR itself to the bare minimum to call
another function, which will be compiled by GCC as a signal.
This means all interrupt optimizations will be put in place by GCC,
while ISRs can be still written in plain C code, but the overhead is
now much smaller. It has proven to reduce by 20 the number of
instructions for every ISR, mainly pushes/pops, which cuts the clock
cycle count down by 30 cycles (1 cycle for every push, 2 for pop).
In time units, this means 1.1 uSec are saved for every ISR invocation
and every shared ISR now takes only 13 clock cycles more than the
"bare" one.

A new `ISR_SHARED` function type has been defined in `Common.h` to hide
away from the programmer GCC attributes. All new shared interrupt
handling routines should be defined of this type to prevent
stack and registers corruption.

Minor changes were made to `Codec.h` to allow including it in .S files.

### CODE REVIEW

**Comment by MrMoDDoM** [comment]
Furthermore, this solution prevents all interrupt signal handler from being occupied, thus allowing other developers to use them dynamically for their code.

In particular, when a codec uses a port signal, this signal can no longer be reused by other codecs unless the first one is excluded from being compiled.

This pull request address this problem and should not harm any of the codecs or signal handler actually present in the code base.

**Comment by fptrs** [comment]
Hi @ceres-c,
great work so far. You might also want to take a look at assembly macros in order to substitute the code to call isr_funcs within the ISRSharing.S.

**Comment by ceres-c** [comment]
You're right, I didn't think about it in the first place.
For now I'd leave the code as it is; it could be changed later if more copy-paste will be needed, I guess.

**Comment by fptrs** [comment]
I just added it so done is done 👍

**Pull request merged**
