### PR TITLE
chamtool xmodem: pad small dumps

### PR DESCRIPTION
**Pull request by doegox**
Should fix issue #47 (chamtool.py fails uploading small files)

Warning: untested at the moment, I don't have a chameleonmini with me today

### CODE REVIEW

**Comment by ptu** [comment]
small change needed because of the following TypeError
```
File "/tmp/ChameleonMini/Software/Chameleon/XModem.py", line 89, in sendData
    dataBlock += '\x00' * (128 - len(dataBlock))
TypeError: can't concat bytes to str
```

convert string to bytes
`dataBlock += b'\x00' * (128 - len(dataBlock))`

Upload to Chameleon went through.
Successfully uploaded dump file and emulated Moscow Metro Card.

**Comment by doegox** [comment]
ha yes sorry I tested the snipped in  python2 prompt, my bad.
thank you!
I fixed the pull request.

**Comment by doegox** [comment]
I could finally test it, works fine here too.

**Comment by geo-rg** [comment]
Thank you for your work!

**Pull request merged**
