### PR TITLE
Sniff Both Way 14443 

### PR DESCRIPTION
**Pull request by gypsophlia**
Hi,

I did some upgrade of the sniffing function so that it can sniff the traffic of ISO14443 both way:
PICC->PCD and PCI->PICC

The following interrupt vectors are added and used in this code: 
PORTB_INT1_vect , TCD0_CCC_vect, TCD0_CCD_vect, TCD1_CCB_vect

The data from PICC still have the parity bit, the parity bit will be checked and removed in the chamlog python tool. (Please see another PR that I created for chamlog tool upgrade)

Please feel free to test this and if you have any problem, please let me know.

@david-oswald @geo-rg 
Best
Zitai

### CODE REVIEW

**Comment by hydra228** [comment]
Give a detailed manual, how to remake my device, to earn your code?

**Comment by gypsophlia** [comment]
**Instructions**
1. Fetch and checkout this branch
2. Set the device to upgrade mode
2. cd Firmware/Chameleon-Mini/ 
3. make program

**(The following procedures are the same as using the previous logging mode)**
4. Set the configure to ISO14443A_SNIFF (config=ISO14443A_SNIFF)
5. Set the log mode to LIVE or MEMORY
(logmode=Memory is recommended because if the Frame Delay Time is so short, the chameleon may not be able to handle the received data in LIVE mode)
6. Download the log using chamtool or view it live using chamlog tool

WARNING:
All data(Card/SniffingLog) stored in the ChameleonMini may be erased by make program.

**Comment by skuep** [comment]
As one of the original early Hardware Designer and Firmware coder I am Berg curious how you implemented the sniffing in the other direction. Ich remember integrating some basic Hardware functionality but have never had a good idea on how to Implement it in the firmware. 
Can you give a hint? :-)

**Comment by geo-rg** [comment]
Hi Zitai,
your code seems to be very good, I just had a look on it! However, I don't understand why you are using a new codec buffer (CodecBuffer2) for the PICC->PCD traffic. Isn't it possible to re-use CodecBuffer?

Did you test the other functions (iso14443a_reader and emulation) with the new code? Are these still working?

Thanks again for your contribution, great work!

Best
Georg

@gypsophlia

**Comment by geo-rg** [comment]
@skuep He re-uses a lot of code from the ISO14443A reader (PICC->PCD). I guess the DEMOD signal looks similar while sniffing.

**Comment by gypsophlia** [comment]
Hi Georg,

THe ISO14443a_reader and emulation still work, I have separate the new codec for sniffing from the original one, so this new code should not affect other functionalities. 

The reason why 2 codec buffer is used is that I tested my code with a very fast(I mean, very short frame delay time) reader. Then it seems that the reader starts to send a new command before the Chameleon is able to finish processing the sniffed PICC->PCD data. If only one buffer is used, this will overwrite the buffer with PCD->PICC data before the processing of  PICC->PCD data have been finished, as the result, sometimes it may get wrong traces. 

So I used two buffers which will give some additional time for the Chameleon to processing the data.

I also optimised the decoding of PICC->PCD signal so that it can run faster. (commit: https://github.com/emsec/ChameleonMini/pull/180/commits/14e17381533e89cb599f8b42f588856d1c18c8cb)

Best
Zitai 

@geo-rg

**Comment by geo-rg** [comment]
Hi @gypsophlia thanks for your contribution, great work!

**Pull request merged**
