### PR TITLE
Implement Ultralight EV1 functionality

### PR DESCRIPTION
**Pull request by dev-zzo**
This implements support for EV1 cards, both 80 and 164 byte sizes. Not implemented currently:
* Lock bits and protection
* One-time programmable memory
Currently, the card is recognized properly (except the originality check, of course) by the NXP app. I'd appreciate if someone tests the password and counter functionality -- although these should be working fine as is.
It is best to grab a full card image from a proper card first and upload it to the chameleon after setting the config to the EV1 cards so that all the bits are in place; unfortunately, there is no proper "first time setup" hook at the moment.

### CODE REVIEW

**Comment by geo-rg** [comment]
Thanks a lot for your contribution!

**Comment by dev-zzo** [comment]
You might also want to update the wiki page with the supported devices list. :-)

**Comment by geo-rg** [comment]
Almost forgotten, thanks! :)

**Comment by skuep** [comment]
This is really cool! I am impressed by the effort that you (and others) have put into transforming the MF Ultralight code that I wrote originally :-)

**Pull request merged**
